export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';
export const UPGRADE = 'UPGRADE_APP';

export const CHANEG_NOTIFICATION_MESSAGE = 'CHANEG_NOTIFICATION_MESSAGE';

export const SET_WALLET = 'SET_WALLET';
export const UPDATE_POINTS = 'UPDATE_POINTS';
export const UPDATE_ADRESSES_ARR = 'UPDATE_ADRESSES_ARR';
export const SELECT_MY_ADDRESS = 'SELECT_MY_ADDRESS';
 export const UPDATE_IMAGE = 'UPDATE_IMAGE';
export const UPDATE_ONLY_PREVIEW = 'UPDATE_ONLY_PREVIEW';
export const UPDATE_CADOO = 'UPDATE_CADOO';
export const FATHER_ATTENDACE = 'FATHER_ATTENDACE';
export const UPDATE_CREDIT = 'UPDATE_CREDIT';

export const BUNDLE_ID_SET = 'BUNDLE_ID_SET';
export const BUNDLE_HOUR_SET = 'BUNDLE_HOUR_SET';
export const BUNDLE_DAYS_SET = 'BUNDLE_DAYS_SET';
export const BUNDLE_OR_ORDER = 'BUNDLE_OR_ORDER';
 

export const CHAHNGE_PAYMENT_FEATURE_STATUS = 'CHAHNGE_PAYMENT_FEATURE_STATUS';
export const CHAHNGE_FIXING_MODE_STATUS = 'CHAHNGE_FIXING_MODE_STATUS';

export const UPLOAD_IMAGE_REG = 'UPLOAD_IMAGE_REG';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const APP_VISITED_CHANGE = 'APP_VISITED_CHANGE';


export const CLEAR_REDUX_DATA = 'CLEAR_REDUX_DATA';

export const LOAD_ON = 'LOAD_ON';
export const LOAD_OFF = 'LOAD_OFF';

export const SET_MAIN_CATEGORY = 'SET_MAIN_CATEGORY';
export const UPDATE_ORDER_DATA = 'UPDATE_ORDER_DATA';
export const SET_ORDER_TYPE = 'SET_ORDER_TYPE';
export const SET_ORDER_SCHEDULING_TYPE = 'SET_ORDER_SCHEDULING_TYPE';
export const FLUSH_ORDER_DATA = 'FLUSH_ORDER_DATA';
export const REMOVE_SERVICE_FORM_ARR = 'REMOVE_SERVICE_FORM_ARR';
export const UPDATE_ORDER_NOTES = 'UPDATE_ORDER_NOTES';
 

export const DOC_GET = 'DOC_GET';
export const DOC_LABEL_SET = 'DOC_LABEL_SET';

export const FAQ_GET = 'FAQ_GET';

 

export const CHANGE_MODAL = 'CHANGE_MODAL';
export const SHOW_MY_POS = 'SHOW_MY_POS';

export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const SHOW_COUNTRY_MODAL = 'SHOW_COUNTRY_MODAL';
export const SET_COUNTRIES_ARR = 'SET_COUNTRIES_ARR';


export const SET_TEMP_USER_MODEL = 'SET_TEMP_USER_MODEL';

//Paymon Actoins
export const CLEAR_PAYMOB = 'CLEAR_PAYMOB';
export const SET_TOKEN_PAYMOB_FIRST = 'SET_TOKEN_PAYMOB_FIRST';
export const SET_AMOUNT_CENTENT = 'SET_AMOUNT_CENTENT'; //for card only
export const SET_ORDER_ID = 'SET_ORDER_ID';
export const SET_PAYMENT_TOKEN_LAST = 'SET_PAYMENT_TOKEN_LAST';
export const SET_HTML_CODE = 'SET_HTML_CODE';
export const CHANGE_PAYMOB_PROCESSING = 'CHANGE_PAYMOB_PROCESSING';
export const CHANGE_TOKEN_STATE = 'CHANGE_TOKEN_STATE';
export const CHANGE_ORDER_ID_STATE = 'CHANGE_ORDER_ID_STATE';
export const CHANGE_PAYMENT_TOKEN_LAST_STATE = 'CHANGE_PAYMENT_TOKEN_LAST_STATE';
export const CHANGE_HTML_CODE_STATE = 'CHANGE_HTML_CODE_STATE';
export const CHANGE_PAYMOB_KOISK_AMOUNT = 'CHANGE_PAYMOB_KOISK_AMOUNT';
export const SET_PAYMOB_REF_NUM = 'SET_PAYMOB_REF_NUM';
export const CLEAR_PAYMOB_REF_NUM = 'CLEAR_PAYMOB_REF_NUM';


//Fawry Actions
export const SET_FAWRY_REF_NUM = 'SET_FAWRY_REF_NUM';
export const CLEAR_FAWRY_REF_NUM = 'CLEAR_FAWRY_REF_NUM';
export const CHANGE_FAWRY_KOISK_AMOUNT = 'CHANGE_FAWRY_KOISK_AMOUNT';
export const CHANGE_FAWRY_PROCESSING = 'CHANGE_FAWRY_PROCESSING';

export const CHANGE_APP_LANG = 'CHANGE_APP_LANG';

// 